#! /bin/sh -e
# Usage:
# ./backup
# doas -u "$(\ls -l ./backup | awk '{print $3}')" ./backup

user="$(stat -c %U ./backup)" ||
user="$(\ls -l ./backup | awk '{print $3}')"

# remote_url="$("$@" git remote -v 2> /dev/null | \
remote_url="$(doas -u "$user" git remote -v 2> /dev/null | \
	grep fetch | grep origin | awk '{print $2}')"
echo "\$remote_url = $remote_url"
[ ! -z "${remote_url:+x}" ] && [ -z "${remote_url##*"kiss"*}" ] || {
	printf '%s\n' "Not the correct path"
	exit 1
}

doas -u "$user" rsync -aqz --exclude ".backup" --exclude ".git*" --delete-excluded ./. ./.backup/
doas -u "$user" sync
